### ISSUE TITLE
[20.07.01] - 모각코 수요 모임

### ISSUE THREAD

**Issue by bluelion2** [bluelion2/Wednesday_Salon#1]
# 20.07.01 수요 모임입니다.

- 장소 : 서울대입구역 "여기는 카페다"
- 시간 : 저녁 8시 ~ 10 시

**Comment by bluelion2** [comment]
이번주는 꼭 참석할게요~!

**Comment by bluelion2** [comment]
- [실용주의 프론트엔드 개발 7장](https://peter-cho.gitbook.io/book/9) - 개발론을 읽어보기

**Comment by wacilpong** [comment]
- 프로그래밍 언어론 부프로그램 챕터 읽기
- What I Learned 포스트 작성하기

**Comment by rjcnd105** [comment]
SAFE 스텍 기본 템플릿 분석
F# 문법 공부

**Comment by bluelion2** [comment]
## 회고 
- [실용주의 프론트엔드 개발7 리뷰](https://bluelion2.github.io/daily_read/2020/07/01/%EC%8B%A4%EC%9A%A9%EC%A3%BC%EC%9D%98_%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%94%EB%93%9C%EA%B0%9C%EB%B0%9C_%EB%A6%AC%EB%B7%B07/)

결론 

- 에러처리의 주체를 정하고 일관성 있게 가는것이 좋다고 생각한다.
- 재사용성에 대한 고민은 항상 가지고 있어야 한다.
- 기획이 부족할 수록 개발 관련 문서를 잘 남기자. 그래야 내가 편하고, 당당해진다.

**Comment by bluelion2** [comment]
<img width="401" alt="스크린샷 2020-07-01 오후 9 25 50" src="https://user-images.githubusercontent.com/34129711/86243560-8c0e3b00-bbe1-11ea-8859-a8486f292697.png">
<img width="390" alt="스크린샷 2020-07-01 오후 9 25 56" src="https://user-images.githubusercontent.com/34129711/86243548-89134a80-bbe1-11ea-9d9e-8d949a0d7609.png">

결론

- 기능 개발을 하는 동안에, 시간과의 싸움 때문에 기술부채는 쌓일 수 밖에 없다. 
- 너무 쌓는것도 안좋지만, 그렇다고 너무 안쌓기 위해 붙잡고만 있을 수는 없다는 것을 인정해야 한다.
- 나중에 기술부채를 잘 털기위해, 기록을 잘 하자.

[출처 : Facebook - 조은 님](https://www.facebook.com/eun.cho.161/posts/3076856639063960)

**Comment by wacilpong** [comment]
### 회고
- [What I Learned 포스트 작성](https://wacilpong.github.io/blog/learned/what-i-learned-2020/#2020-07-01)
- 프로그래밍 언어론 제 10장 부프로그램 읽음
  - 디폴트 매개변수를 갖는 중복 서브프로그램(함수!!!)은 안티패턴
    ```
    void fun(float b = 0.0);
    void fun();
    ...
    func();
    ```
  - 클로저 -> 대부분 스크립트 언어에서 지원, 정적 스코프 언어
  - 코루틴 -> resume과 suspend할 수 있는 루틴! ex. javascript async/await, generator
  - 스택-동적 변수 -> 함수의 지역변수가 스택-동적이어야 재귀 호출이 가능해진다.

**Comment by rjcnd105** [comment]
회고
- https://gggururu.tistory.com/62
- F# Record{}, Tuple(*), Option(like haskell maybe)
