### ISSUE TITLE
[20.07.08] - 모각코 수요 모임 

### ISSUE THREAD

**Issue by bluelion2** [bluelion2/Wednesday_Salon#2]
# ❤ 수요 살롱

## 📅  7월 8일

☕ 장소 : 서울대입구역

⏱️ 시간 : 수요일 저녁 8시 ~ 10시

🙏 참석하실 분은 밑에 이슈 등록해주세요~!

**Comment by wacilpong** [comment]
참석~

**Comment by bluelion2** [comment]
참석합니다~

**Comment by bluelion2** [comment]
실용주의 프론트엔드 개발 13장 [성능 최적화](https://peter-cho.gitbook.io/book/13) 를 읽어보고 느낀점 써보기

**Comment by wacilpong** [comment]
- VSync + requestFrameAnimation 정리하기
- 프로그래밍 언어론 서브프로그램 읽기

**Comment by rjcnd105** [comment]
F# SAFE STACK 분석

**Comment by bluelion2** [comment]
회고 
 - [NHN TOAST 성능최적화](https://ui.toast.com/fe-guide/ko_PERFORMANCE/#%EB%A7%8C%EB%8A%A5-%EC%9C%A0%ED%8B%B8-%EC%82%AC%EC%9A%A9-%EC%A3%BC%EC%9D%98%ED%95%98%EA%B8%B0)
 일부분을 읽고 느낀점을 써봄. [link](https://github.com/bluelion2/bluelion2.github.io/commit/595638699592e6b50527d62006f2063eb41af85a)

**Comment by wacilpong** [comment]
#### 회고
- VSync: GPU가 처리하는 프레임, 브라우저에서도 VSync 내에서 프레임 렌더링 (16.6ms)
- [크롬 브라우저에서의 렌더링](https://developers.google.com/web/fundamentals/performance/rendering)
- [블로그에 정리했음](https://wacilpong.github.io/blog/learned/what-i-learned-2020/#2020-07-08)

**Comment by rjcnd105** [comment]
![image](https://user-images.githubusercontent.com/10142672/86920073-1a476b80-c164-11ea-92c4-b57a439daca5.png)
각각의 Enum속 애들이 각각의 심볼 타입? 이 됨 싱기방기

**Comment by bluelion2** [comment]
고생하셨습니다!
