### ISSUE TITLE
[20.12.09] 모각코 수요 스터디 (곱창모임)

### ISSUE THREAD

**Issue by bluelion2** [bluelion2/Wednesday_Salon#23]
# ❤ 수요 살롱

## 📅 12월 09일

☕ 장소 : 서울대입구역 황소곱창

⏱️ 시간 : 수요일 저녁 8시 ~ 10시

🙏 참석하실 분은 밑에 이슈 등록해주세요~!

**Comment by wacilpong** [comment]
참석 곱창파티 오예르

**Comment by ds2lvg** [comment]
이날은 무조건 참석

**Comment by bluelion2** [comment]
참석~

**Comment by bluelion2** [comment]
7일날 거리두기 발표에 따라서 변경될 수 있습니다~

**Comment by bluelion2** [comment]
사회적 거리두기 연장하면서 나중에 하기로... ㅠㅠ
